-- Sprint 19-20: periodic ZK audit reports.
--
-- Stores compliance-officer-facing reports generated by the
-- /v1/audit/reports surface. Tenant-scoped; one row per generated
-- report; signature column holds the operator HMAC over the
-- canonical-form JSON (see core/src/audit/report.rs::sign_report).

CREATE TABLE IF NOT EXISTS audit_reports (
    report_id      TEXT PRIMARY KEY,
    tenant_id      TEXT NOT NULL DEFAULT 'default',
    agent_ids_json TEXT NOT NULL,
    period_start   BIGINT NOT NULL,
    period_end     BIGINT NOT NULL,
    generated_at   BIGINT NOT NULL,
    report_json    TEXT NOT NULL,
    signature      TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_audit_reports_tenant
    ON audit_reports(tenant_id, generated_at);
