apiVersion: v1
kind: Service
metadata:
  name: {{ include "sauronid.fullname" . }}-core
  labels:
    {{- include "sauronid.labels" . | nindent 4 }}
    app.kubernetes.io/component: core
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.core.service.port }}
      targetPort: http
  selector:
    app.kubernetes.io/name: {{ include "sauronid.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: core
