#!/usr/bin/env bash
# scripts/lib/dev_secrets.sh
#
# Shared helper used by every local-orchestration script (quickstart.sh,
# launch.sh, run-all.sh, start.sh, core/seed.sh, smoke scripts, ...) to load
# or generate a dev-only admin key. There are no checked-in default tokens —
# the value is generated on first use and cached in `.dev-secrets` at the
# repo root so subsequent scripts in the same session pick up the same key.
#
# Usage:
#   source "$REPO_ROOT/scripts/lib/dev_secrets.sh"
#   load_dev_admin_key   # exports SAURON_ADMIN_KEY (and writes .dev-secrets)
#
# Behaviour:
#   - If SAURON_ADMIN_KEY is already set in the environment, use it as-is.
#   - Else if .dev-secrets exists, source it.
#   - Else generate a fresh hex secret via openssl and persist it.
#
# Production deployments MUST set SAURON_ADMIN_KEY explicitly (and ENV=production);
# this helper is for local development only.

# Resolve the repository root from this file's location so callers do not have
# to pass it in.
_SAURON_DEV_SECRETS_LIB_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
_SAURON_DEV_SECRETS_REPO_ROOT="$(cd "${_SAURON_DEV_SECRETS_LIB_DIR}/../.." && pwd)"
SAURON_DEV_SECRETS_FILE="${SAURON_DEV_SECRETS_FILE:-${_SAURON_DEV_SECRETS_REPO_ROOT}/.dev-secrets}"

load_dev_admin_key() {
    if [[ -n "${SAURON_ADMIN_KEY:-}" ]]; then
        export SAURON_ADMIN_KEY
        return 0
    fi

    if [[ -f "${SAURON_DEV_SECRETS_FILE}" ]]; then
        # shellcheck disable=SC1090
        source "${SAURON_DEV_SECRETS_FILE}"
    fi

    if [[ -z "${SAURON_ADMIN_KEY:-}" ]]; then
        if ! command -v openssl >/dev/null 2>&1; then
            echo "[dev-secrets] openssl not installed; cannot generate dev admin key." >&2
            echo "              Set SAURON_ADMIN_KEY in your env and re-run." >&2
            return 1
        fi
        SAURON_ADMIN_KEY="$(openssl rand -hex 32)"
        umask 077
        {
            echo "# Generated by scripts/lib/dev_secrets.sh — local dev only, gitignored."
            echo "SAURON_ADMIN_KEY=${SAURON_ADMIN_KEY}"
        } > "${SAURON_DEV_SECRETS_FILE}"
        echo "[dev-secrets] generated fresh SAURON_ADMIN_KEY → ${SAURON_DEV_SECRETS_FILE}" >&2
    fi

    export SAURON_ADMIN_KEY
}

require_admin_key() {
    # For scripts that should NEVER auto-generate (e.g. tests that target an
    # already-running server). Fail loudly if the operator forgot to source
    # .dev-secrets / export the key.
    if [[ -z "${SAURON_ADMIN_KEY:-}" ]]; then
        if [[ -f "${SAURON_DEV_SECRETS_FILE}" ]]; then
            # shellcheck disable=SC1090
            source "${SAURON_DEV_SECRETS_FILE}"
        fi
    fi
    if [[ -z "${SAURON_ADMIN_KEY:-}" ]]; then
        echo "[dev-secrets] SAURON_ADMIN_KEY not set and no .dev-secrets file found." >&2
        echo "              Run quickstart.sh / launch.sh first, or export the key" >&2
        echo "              manually (openssl rand -hex 32)." >&2
        return 1
    fi
    export SAURON_ADMIN_KEY
}
